#!/bin/bash

#
# generate issue file on stdout
# snippets needs to be put in /etc/issue.d, /run/issue.d/ or
# /usr/lib/issue.d
# snippets are sorted for output
# the script assumes this directory exist already, else it will fail
#

PREFIX=""

declare -A FILES

find_files() {
    for f in ${PREFIX}/usr/lib/issue.d/* ${PREFIX}/run/issue.d/* ${PREFIX}/etc/issue.d/* ; do
	test -f "$f" || continue
	T=`basename "$f"`
	FILES[${T}]="$f"
    done
}

generate_issue() {
    for key in "${!FILES[@]}"; do
	keys="${keys}\n${key}";
    done
    for key in `echo -e ${keys} | sort -u`; do
	cat "${FILES[$key]}"
    done
}

usage() {
    echo "Usage: issue-generator [--prefix <path]"
    echo "           issue-generator network add|remove interface"
    exit $1
}

while [ 1 ]; do
    if [ $# -eq 0 ]; then
        break
    fi

    case "$1" in
	network)
	    if [ $# -ne 3 ]; then
		usage 1;
	    fi

	    case "$2" in
		add)
		    echo "${3}: \\4{$3} \\6{$3}" > "${PREFIX}/run/issue.d/70-$3.conf"
		    ;;
		del|delete|rm|remove)
		    rm -f "${PREFIX}/run/issue.d/70-$3.conf"
		    ;;
	    esac
	    shift 3;
	    ;;
	--prefix)
	    PREFIX=$2
	    shift 2
	    ;;
	*)
	    if [ $# -ge 1 ]; then
		usage 1;
	    fi
	    ;;
    esac
done

find_files
generate_issue > ${PREFIX}/run/issue
